SectorTag = {
    AboveWaterSector: 1,
    BelowWaterSector: 2,
    Boss2RoamSector: 3,
    StarTrekDoor: 9,
    TransportElevator: 15,
    ElevatorPlatformDown: 16,
    ElevatorPlatformUp: 17,
    ElevatorDown: 18,
    ElevatorUp: 19,
    CeilingDoor: 20,
    FloorDoor: 21,
    SplitDoor: 22,
    SwingingDoor: 23,
    Reserved: 24,
    SlidingDoor: 25,
    SplitStarTrekDoor: 26,
    StretchingShrinkingSector: 27,
    FloorRiseCeilingDrop: 28,
    TeethDoor: 29,
    RotateRiseSector: 30,
    TwoWayTrain: 31,
    OneTimeSound: 10000,
    SecretPlace: 32767,
    EndOfLevelWithMessage: 65534,
    EndOfLevel: 65535
}